# Emoji Converter --Basic version(No if, No Loop)
msg = input("Enter your message : ")
msg = msg.replace(":)", "🙂")
msg = msg.replace(":(", "☹️")
msg = msg.replace(":D", "😀")
msg = msg.replace(";)", "😉")
msg = msg.replace("*_*", "😍")
print(msg)